{{- $autoscalingv2 := .Capabilities.APIVersions.Has "autoscaling/v2" -}}
{{- if and (.Values.querier.horizontalPodAutoscaling.enabled) (not .Values.querier.kedaAutoscaling.enabled) }}
{{- if $autoscalingv2 }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "querier") }}
  namespace : {{ .Release.Namespace | quote }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "querier") | nindent 4 }}
  annotations:
    {{- toYaml .Values.querier.annotations | nindent 4 }}
spec:
  scaleTargetRef:
    metrics: []
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mimir.resourceName" (dict "ctx" . "component" "querier") }}
  minReplicas: {{ .Values.querier.horizontalPodAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.querier.horizontalPodAutoscaling.maxReplicas }}
  {{- with .Values.querier.horizontalPodAutoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
  {{- with .Values.querier.horizontalPodAutoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if $autoscalingv2 }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
  {{- with .Values.querier.horizontalPodAutoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if $autoscalingv2 }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
{{- end }}
